language: node_js
node_js:
  - stable
script:
  - set -e
  - npm run build
  - npm run test
  - npm run coverage
  - rm -rf src
  - mv dist src
  - npm run test
cache:
  - node_modules
after_success:
  - bash <(curl -s https://codecov.io/bash)
