language: node_js
node_js:
  - v6
script:
  - set -e
  - npm run build
  - rm -rf src; ln -s dist src;
  - npm run test
  - npm run coverage
cache:
  - node_modules
after_success:
  - bash <(curl -s https://codecov.io/bash)
